[[pages]]
path = "app.py"
name = "Home"
icon = ":basketball:"

[[pages]]
path = "pages/styler_page.py"
name = "AgStyler Module"
icon = ":books:"

[[pages]]
path = "pages/formatter.py"
name = "AgGrid Formatter"
icon = ":memo:"

[[pages]]
path = "pages/highlighting.py"
name = "Highlighting"
icon = ":high_brightness:"

[[pages]]
path = "pages/edit.py"
name = "Cells Editing"
icon = ":pencil2:"

[[pages]]
path = "pages/about.py"
name = "About"
icon = ":question:"